global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "estate-backend-local"
    metrics_path: "/api/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "Real Estate Backend Service (Local Host)"

  - job_name: "estate-backend-docker"
    metrics_path: "/api/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["estate-service:8080"]
        labels:
          application: "Real Estate Backend Service (Docker Container)"
