server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'
        # include: health,prometheus,metrics